CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  user_type ENUM('RIDER', 'DRIVER') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE rides (
  id VARCHAR(36) PRIMARY KEY AUTO_INCREMENT,
  rider_id VARCHAR(36) NOT NULL,
  driver_id VARCHAR(36),
  pickup VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  status ENUM('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED') NOT NULL,
  fare DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (rider_id) REFERENCES users(id),
  FOREIGN KEY (driver_id) REFERENCES users(id)
);

CREATE TABLE carpools (
  id VARCHAR(36) PRIMARY KEY AUTO_INCREMENT,
  driver_id VARCHAR(36) NOT NULL,
  route VARCHAR(255) NOT NULL,
  seats INT NOT NULL,
  departure_time DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (driver_id) REFERENCES users(id)
);

